name: minsk8
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_map:
    git:
      url: git://github.com/okaxaki/flutter_map.git
      ref: fix/support-flutter-1.10
  latlong: ^0.6.1
  permission_handler: ^4.0.0
  geolocator: ^5.1.5
  state_persistence: ^0.0.7

  firebase_core: 0.4.5
  firebase_storage: 3.1.6
  firebase_dynamic_links: 0.5.1
  firebase_analytics: 5.0.16

  image_cropper: 1.1.1
  image_picker: ^0.6.7

  # transparent_image: 1.0.0
  pinch_zoom_image:
    git:
      url: git@github.com:TheFe91/pinch_zoom_image.git

  extended_image: ^0.7.3+1
  like_button: 1.0.1
  loading_more_list: 3.0.0
  http_client_helper: ^0.2.1
  extended_nested_scroll_view:
    1.0.1
    # path: ../extended_nested_scroll_view/
    # git: git://github.com/comerc/extended_nested_scroll_view.git
  pull_to_refresh_notification:
    0.3.5
    # path: ../pull_to_refresh_notification/
    # git: git://github.com/comerc/pull_to_refresh_notification.git
  share: 0.6.4+3

  json_annotation: 3.0.1
  enum_to_string: 1.0.8
  graphql_flutter: 3.0.0

  carousel_slider: 1.4.0
  sliding_up_panel: 0.3.6
  auto_orientation: 1.0.6
  font_awesome_flutter: 8.5.0

  flutter_markdown: 0.3.2
  # webview_flutter: 0.3.22+1

  provider: 4.1.3

  flutter_typeahead: 1.8.7
  recursive_regex: 0.1.3+2

  characters: 1.0.0

  # flutter_screenutil: 2.2.0

  flutter_local_notifications: 1.4.4+2
  rxdart: 0.23.1

  package_info: 0.4.1

  intl: 0.16.1

  url_launcher: 5.5.0
  launch_review: 2.0.0

  rainbow_color: 0.1.1

  # for markdown_builder.dart
  markdown: 2.1.7
  build: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 1.7.2
  json_serializable: 3.2.3

  pedantic: ^1.0.0
  # effective_dart: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
